# Bakcend Dockerfile

# Base Image
FROM node:18

# Working Directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . . 

# Port
EXPOSE 5000

# Health checking
HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl -f http://localhost:5000 // exit 1

# Run the application
CMD ["npm", "start"]